name: impostormx
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  # Gestión de estado
  provider: ^6.0.5
  # Vibración avanzada (NUEVO)
  vibration: ^3.1.5
  # Pantalla encendida
  wakelock_plus: ^1.1.4
  # Fuentes e iconos
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  audioplayers: ^6.5.1
  # Iconos estilo iOS
  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.5.0
  shared_preferences: ^2.5.4
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/

  fonts:
    - family: Bungee
      fonts:
        - asset: assets/fonts/Bungee-Regular.ttf

    - family: YoungSerif
      fonts:
        - asset: assets/fonts/YoungSerif-Regular.ttf
